apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: n8n

resources:
  - namespace.yaml
  - n8n-deployment.yaml
  - n8n-service.yaml
  - n8n-ingress.yaml
  - n8n-hpa.yaml
  - postgres-statefulset.yaml
  - redis-statefulset.yaml
  - keycloak-deployment.yaml
  - keycloak-service.yaml
  - backup/backup-cronjob.yaml
  - backup/backup-pvc.yaml
  - monitoring/business-metrics-deployment.yaml
  - ai-analytics/predictive-analytics-deployment.yaml
  - gpt-integration/gpt-service-deployment.yaml
  - vault/vault-deployment.yaml
  - opentelemetry/otel-collector-deployment.yaml
  - federation/federation-controller-deployment.yaml

configMapGenerator:
  - name: n8n-config
    files:
      - config/n8n-config.json
  - name: redis-config
    files:
      - redis.conf
  - name: backup-config
    literals:
      - s3_bucket=n8n-backups
  - name: metrics-collector-config
    files:
      - monitoring/collector.py
  - name: predictor-config
    files:
      - ai-analytics/config.yaml
  - name: predictor-code
    files:
      - ai-analytics/predictor.py
  - name: vault-config
    files:
      - vault/config/vault.hcl
  - name: otel-collector-config
    files:
      - opentelemetry/config/config.yaml
  - name: cluster-config
    literals:
      - name=cluster-1
      - primary=true

secretGenerator:
  - name: n8n-secrets
    files:
      - secrets/n8n-secrets.env
  - name: keycloak-secrets
    literals:
      - admin_user=admin
      - admin_password=changeme
      - db_user=keycloak
      - db_password=changeme
  - name: aws-secrets
    literals:
      - access_key=changeme
      - secret_key=changeme
  - name: slack-secrets
    literals:
      - webhook_url=changeme
  - name: vault-aws-secrets
    files:
      - secrets/vault-aws-secrets.env
  - name: openai-secrets
    files:
      - secrets/openai-secrets.env

images:
  - name: n8nio/n8n
    newTag: latest
  - name: postgres
    newTag: 13-alpine
  - name: redis
    newTag: 6-alpine
  - name: quay.io/keycloak/keycloak
    newTag: latest
  - name: prom/pushgateway
    newTag: latest
  - name: python
    newTag: 3.9-slim
  - name: predictive-analytics
    newName: n8n-predictive-analytics
    newTag: latest
  - name: vault
    newTag: 1.13.3
  - name: otel/opentelemetry-collector
    newTag: 0.81.0
  - name: gpt-service
    newTag: latest
  - name: federation-controller
    newTag: latest

patches:
  - path: patches/resource-limits.yaml
    target:
      kind: Deployment
  - path: patches/hpa-settings.yaml
    target:
      kind: HorizontalPodAutoscaler 