apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: n8n
  namespace: n8n
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: n8n
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  - type: Pods
    pods:
      metric:
        name: workflow_executions_per_second
      target:
        type: AverageValue
        averageValue: 10
  - type: Object
    object:
      metric:
        name: error_rate_percentage
      describedObject:
        apiVersion: apps/v1
        kind: Deployment
        name: n8n
      target:
        type: Value
        value: 5
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Pods
        value: 2
        periodSeconds: 60
      - type: Percent
        value: 100
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 1
        periodSeconds: 300
      - type: Percent
        value: 20
        periodSeconds: 300 