# Valores globais
global:
  environment: production
  namespace: n8n
  domain: n8n.example.com
  imagePullSecrets: []

# Configurações do N8N
n8n:
  replicaCount: 3
  image:
    repository: n8nio/n8n
    tag: latest
    pullPolicy: Always
  
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 4Gi
  
  persistence:
    enabled: true
    size: 10Gi
    storageClass: standard

# GPT Service
gpt:
  enabled: true
  replicaCount: 2
  image:
    repository: n8n-enterprise/gpt-service
    tag: latest
  
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi

# Vault
vault:
  enabled: true
  server:
    dev:
      enabled: false
    ha:
      enabled: true
      replicas: 3
    
    dataStorage:
      size: 10Gi
    
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 1000m
        memory: 2Gi

# OpenTelemetry
opentelemetry:
  enabled: true
  mode: deployment
  replicaCount: 2
  
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi

# Jaeger
jaeger:
  enabled: true
  allInOne:
    enabled: false
  collector:
    enabled: true
    replicaCount: 2
  agent:
    enabled: true
  query:
    enabled: true
    replicaCount: 2

# Prometheus
prometheus:
  enabled: true
  server:
    retention: 15d
    persistentVolume:
      size: 50Gi
  
  alertmanager:
    enabled: true
    persistentVolume:
      size: 2Gi

# Grafana
grafana:
  enabled: true
  persistence:
    enabled: true
    size: 10Gi
  
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: default
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default

# Federation
federation:
  enabled: true
  replicaCount: 2
  image:
    repository: n8n-enterprise/federation
    tag: latest
  
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi

# AI Analytics
aiAnalytics:
  enabled: true
  replicaCount: 2
  image:
    repository: n8n-enterprise/ai-analytics
    tag: latest
  
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 4Gi
  
  persistence:
    enabled: true
    size: 20Gi
    storageClass: standard

# Ingress
ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  
  hosts:
    - host: n8n.example.com
      paths:
        - path: /
          pathType: Prefix
  
  tls:
    - secretName: n8n-tls
      hosts:
        - n8n.example.com

# Métricas e Monitoramento
metrics:
  serviceMonitor:
    enabled: true
    namespace: monitoring
  
  prometheusRule:
    enabled: true
    namespace: monitoring
    rules:
      - alert: HighErrorRate
        expr: rate(n8n_errors_total[5m]) > 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          description: High error rate detected in N8N

# Backup
backup:
  enabled: true
  schedule: "0 2 * * *"
  retention: 7
  destination: s3://n8n-backups
  s3:
    bucket: n8n-backups
    region: us-east-1 